import { AccountRepositoryDatabase } from "./AccountRepository.ts";
import API from "./api.ts";
import { PgPromiseAdapter } from "./DatabaseConnection.ts";
import { Deposit } from "./Deposit.ts";
import { ExecuteOrder } from "./ExecuteOrder.ts";
import { GetAccount } from "./GetAccount.ts";
import { GetOrder } from "./GetOrder.ts";
import Mediator from "./Mediator.ts";
import OrderHandler from "./OrderHandler.ts";
import { OrderRepositoryDatabase } from "./OrderRepository.ts";
import { PaymentGatewayHttp } from "./PaymentGateway.ts";
import { PlaceOrder } from "./PlaceOrder.ts";
import { Signup } from "./Signup.ts";

const databaseConnection = new PgPromiseAdapter();
const accountRepository = new AccountRepositoryDatabase(databaseConnection);
const orderRepository = new OrderRepositoryDatabase(databaseConnection);
const paymentGateway = new PaymentGatewayHttp();
const signup = new Signup(accountRepository);
const getAccount = new GetAccount(accountRepository);
const deposit = new Deposit(accountRepository, paymentGateway);
const executeOrder = new ExecuteOrder(orderRepository);
const mediator = new Mediator();
new OrderHandler(mediator, executeOrder);
const placeOrder = new PlaceOrder(accountRepository, orderRepository, mediator);
const getOrder = new GetOrder(orderRepository);
new API(signup, getAccount, deposit, placeOrder, getOrder);
